### ISSUE TITLE
How to start a program like this one.

### ISSUE THREAD

**Issue by Zhou-Xuanyu** [str-ct/locatle#3]
## Dude, I love this program very much.
I am a high school students in China and interested in both geoguessr and CS. However in our school, there is no one to consulting to about these stuff. One day when I was surfing on BILIBILI(generally Chinese youtube), I accidentally spotted someone was practising GEO on your website. And I found this on github, so I was wondering what should I learn as a beginner to make a program like this(is there any recommended courses or books). Thank you so much.
## already starred

**Comment by PaddiM8** [comment]
Thanks! That's great to hear. I made this with HTML, CSS, JavaScript and Python. HTML/CSS for the design, JavaScript for the website's functionality, and Python for generating the data that the website uses. You don't need to know the languages in-depth to be able to do something like this, it's quite simple. If you're interested in making websites you should start with HTML and CSS and then learn some JavaScript as well. I don't have any resources since I just learn by doing and looking at examples.
